//created on: 20 mar 2021
package test

//list any import classes here.
import it.unicam.cs.model.Grid;
import it.unicam.cs.model.Square;
import it.unicam.cs.enumeration.SquareType;
import it.unicam.cs.enumeration.SquareState;
import it.unicam.cs.model.Location;
import it.unicam.cs.model.MinesweeperEvent;
import it.unicam.cs.enumeration.MinesweeperEventAction;
import java.util.ArrayList;


//declare any global variables here




rule "Your First Rule"

    when
        Grid( )
    then
        //actions
        System.out.println("Grid Created!");

end

rule "Populate Grid"

	when
		$grid : Grid(isPopulated() == false)
	then
		$grid.populate();
		System.out.println($grid);
end
/*
rule "Print Location"

	when
		$loc : Location( )
	then
		System.out.println("Row: " + $loc.getRow() + " Column: " + $loc.getColumn());

end
*/
rule "Print all Locations"
    when
        $loc : ArrayList( )
        	   from collect( Location( ) )
    then
        System.out.println($loc);
end

rule "Print all Events"
    when
        $event : ArrayList( )
        	   from collect( MinesweeperEvent( ) )
    then
        System.out.println($event);
end

rule "Print Event Location"

	when
		$event : MinesweeperEvent( )
	then
		System.out.println("Row: " + $event.getLocation().getRow() + " Column: " + $event.getLocation().getColumn());

end


rule "empty square"

	when
		$event : MinesweeperEvent(ACTION == MinesweeperEventAction.UNCOVER)
		$grid : Grid(getSquareAt($event.getLocation()).getType() == SquareType.EMPTY && getSquareAt($event.getLocation()).getState() == SquareState.COVERED)
	then
		System.out.println("Empty Square Rule Fired!");
		$grid.uncoverEmptySquare($event.getLocation());
end

rule "bomb square"

	when
		$event : MinesweeperEvent(ACTION == MinesweeperEventAction.UNCOVER)
		$grid : Grid(getSquareAt($event.getLocation()).getType() == SquareType.BOMB && getSquareAt($event.getLocation()).getState() == SquareState.COVERED)
	then
		System.out.println("Bomb Square Rule Fired!");
		$grid.uncoverBombSquare($event.getLocation());
end

rule "number square"

	when
		$event : MinesweeperEvent(ACTION == MinesweeperEventAction.UNCOVER)
		$grid : Grid(getSquareAt($event.getLocation()).getType() == SquareType.NUMBER && getSquareAt($event.getLocation()).getState() == SquareState.COVERED)
	then
		System.out.println("Number Square Rule Fired!");
		$grid.uncoverNumberSquare($event.getLocation());
end

rule "flag/unflag square"

	when
		$event : MinesweeperEvent(ACTION == MinesweeperEventAction.FLAG)
		$grid : Grid(getSquareAt($event.getLocation()).getState() == SquareState.COVERED || getSquareAt($event.getLocation()).getState() == SquareState.FLAGGED)
	then
		System.out.println("Flag/Unflag Square Rule Fired!");
		$grid.flagUnflagSquare($event.getLocation());
end

rule "chord square"

	when
		$event : MinesweeperEvent(ACTION == MinesweeperEventAction.CHORD)
		$grid : Grid(getSquareAt($event.getLocation()).getType() == SquareType.NUMBER && getSquareAt($event.getLocation()).getState() == SquareState.UNCOVERED)
	then
		System.out.println("Chord Square Rule Fired!");
		$grid.chordSquare($event.getLocation());
end

/*
rule "flag square"

	when
		$event : MinesweeperEvent(ACTION == MinesweeperEventAction.FLAG)
		$grid : Grid(getSquareAt($event.getLocation()).getState() == SquareState.COVERED)
	then
		System.out.println("Flag Square Rule Fired!");
		$grid.flagSquare($event.getLocation());
end

rule "unflag square"

	when
		$event : MinesweeperEvent(ACTION == MinesweeperEventAction.FLAG)
		$grid : Grid(getSquareAt($event.getLocation()).getState() == SquareState.FLAGGED)
	then
		System.out.println("Unflag Square Rule Fired!");
		$grid.unflagSquare($event.getLocation());
end
*/

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
