//created on: 20 mar 2021
package test

//list any import classes here.
import it.unicam.cs.model.Grid;
import it.unicam.cs.model.Square;
import it.unicam.cs.enumeration.SquareType;
import it.unicam.cs.enumeration.SquareState;
import it.unicam.cs.model.Location;
import it.unicam.cs.enumeration.GameState;
import java.util.ArrayList;


//declare any global variables here
/*
rule "Populate Grid"

	when
		$grid : Grid(isPopulated() == false)
	then
		$grid.populate();
		System.out.println($grid);
end

rule "Print all Locations"
	agenda-group "debug"
    when
        $loc : ArrayList( )
        	   from collect( Location( ) )
    then
        System.out.println($loc);
end

rule "Print Event Location"
	agenda-group "debug"
	when
		$loc : Location( )
	then
		System.out.println("Row: " + $loc.getRow() + " Column: " + $loc.getColumn());
end

rule "empty square"
	agenda-group "UNCOVER"
	when
		$loc : Location( )
		$grid : Grid(getSquareAt($loc).getType() == SquareType.EMPTY && getSquareAt($loc).getState() == SquareState.COVERED)
	then
		System.out.println("Empty Square Rule Fired!");
		$grid.newUncoverEmpty($loc);
		$grid.getNeighboursAsStream($loc).filter(s -> s.getState() == SquareState.COVERED).forEach(s -> {
					if (s.getType() == SquareType.NUMBER || s.getType() == SquareType.EMPTY) {
						insert(s.getLocation());
					}
				});
		retract($loc);
end

rule "bomb square"
	agenda-group "UNCOVER"
	when
		$loc : Location( )
		$grid : Grid(getSquareAt($loc).getType() == SquareType.BOMB && getSquareAt($loc).getState() == SquareState.COVERED && getState() == GameState.ONGOING)
	then
		System.out.println("Bomb Square Rule Fired!");
		$grid.uncoverBombSquare($loc);
		retract($loc);
end

rule "number square"
	agenda-group "UNCOVER"
	when
		$loc : Location( )
		$grid : Grid(getSquareAt($loc).getType() == SquareType.NUMBER && getSquareAt($loc).getState() == SquareState.COVERED)
	then
		System.out.println("Number Square Rule Fired!");
		$grid.uncoverNumberSquare($loc);
		retract($loc);
end

rule "flag/unflag square"
	agenda-group "FLAG"
	when
		$loc : Location( )
		$grid : Grid(getSquareAt($loc).getState() == SquareState.COVERED || getSquareAt($loc).getState() == SquareState.FLAGGED)
	then
		System.out.println("Flag/Unflag Square Rule Fired!");
		$grid.flagUnflagSquare($loc);
		retract($loc);
end

rule "chord square"
	agenda-group "CHORD"
	when
		$loc : Location( )
		$grid : Grid(getSquareAt($loc).getType() == SquareType.NUMBER && getSquareAt($loc).getState() == SquareState.UNCOVERED)
	then
		System.out.println("Chord Square Rule Fired!");
		$grid.chordSquare($loc);
		retract($loc);
end
*/